apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task4
spec:
  steps:
    - name: createfile
      image: ubuntu
      command:
        - touch
      args:
        - "/uth/test.txt"
  workspaces:
    - name: working
      mountPath: /uth
