apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task2ubi
spec:
  steps:
    - name: id
      image: registry.access.redhat.com/ubi8/ubi:latest
      command:
        - cat
      args:
        - /etc/redhat-release
    - name: echo
      image: registry.access.redhat.com/ubi8/ubi:latest
      command:
        - echo
      args:
        - "hello world"
    - name: create
      image: registry.access.redhat.com/ubi8/ubi:latest
      command:
        - touch
      args:
        - " test1.txt"
    - name: whereami
      image: registry.access.redhat.com/ubi8/ubi:latest
      command:
        - pwd
    - name: list
      image: registry.access.redhat.com/ubi8/ubi:latest
      command:
        - ls
      args:
        - "-ali"
        - "*"
