apiVersion: v1
kind: ServiceAccount
metadata:
  name: triggersa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: triggersa-eventlistener-binding
subjects:
- kind: ServiceAccount
  name: triggersa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-eventlistener-roles
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: triggersa-eventlistener-clusterbinding
subjects:
- kind: ServiceAccount
  name: triggersa
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-eventlistener-clusterroles
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: triggersa-interceptor-clusterbinding
subjects:
- kind: ServiceAccount
  name: triggersa
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-core-interceptor-secrets
