apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: eventlistener1
spec:
# serviceAccountName: triggersa
  triggers:
  - bindings:
    - ref: triggerbinding1
    template:
      ref: triggertemplate1
